version: 1.0.{build}
image: Visual Studio 2019
install:
- appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v5.8.0/nuget.exe
before_build:
- nuget restore
build:
  verbosity: minimal
#cache:
#  - packages -> **\packages.config
